import React from "react";
import Head from "next/head";
import Header from "../sections/Header";
import Footer from "../sections/Footer";
// Mobile
import MobileFooter from "../sections/MobileFooter";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Remote Landing Page</title>
        <meta
          name="description"
          content="Remote Landing Page Generated by Next App and Typescript"
        />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta property="og:title" content="remote-work-page" />
        <meta property="og:type" content="landing page" />
        <meta property="og:description" content="remote.description" />
        <link rel="icon" href="/images/remoteIcon.png" />
      </Head>

      {/* Header, Main & Footer */}
      <div className="flex flex-col min-h-screen">
        <Header />
        {/* Mobile Visibility */}
        {/* <MenuDropdown /> */}
        <main className="flex-grow">{children}</main>
        <Footer />
        <MobileFooter />
      </div>
    </>
  );
};
export default Layout;
