import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/Navbar";
import NavbarDropdown from "../components/NavbarDropdown";


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Remote Landing Page</title>
        <meta
          name="description"
          content="Remote Landing Page Generated by Next App and Typescript"
        />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta property="og:title" content="remote-work-page"/>
        <meta property="og:type" content="landing page" />
        <meta property="og:description" content="remote.description" />
        <link rel="icon" href="/images/favicon.ico" />
      </Head>

      <main>
        <Navbar />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
