import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
          <h1 className='flex justify-center text-3xl font-bold text-sky-600'>
              Hello World
          </h1>
      </main>

      <footer>
   
      </footer>
    </div>
  )
}

export default Home
